name: CI with gtest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libgtest-dev

      
      - name: Build gtest
        run: |
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib

      
      - name: Configure and build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure